import { EvolutionLevel } from '../types/game';

export const MILESTONE_LEVELS: Record<number, number> = {
  11: 2048,
  12: 4096,
  13: 8192,
  14: 16384,
  15: 32768,
  16: 65536,
  17: 131072,
  18: 262144,
};

export const EVOLUTION_LEVELS: EvolutionLevel[] = [
  {
    level: 1,
    name: 'Tuerca',
    shortName: 'Tuerca',
    era: 'Componentes Mecánicos',
    yearRange: 'Fase I',
    description: 'Componente forjado en acero templado, rosca métrica de precisión y base estructural.',
    image: '1.png',
    bgGradient: 'from-slate-950 via-zinc-900 to-black',
    borderColor: 'border-cyan-500/70',
    textColor: 'text-cyan-300',
    accentColor: '#06b6d4',
    glowColor: 'rgba(6, 182, 212, 0.6)',
    glowColorSoft: 'rgba(6, 182, 212, 0.25)',
    hpPoints: 2,
  },
  {
    level: 2,
    name: 'Engranaje',
    shortName: 'Engranaje',
    era: 'Transmisión & Torque',
    yearRange: 'Fase II',
    description: 'Dientes sincronizados de alta fricción para transferir torque y movimiento continuo.',
    image: '2.png',
    bgGradient: 'from-cyan-950 via-zinc-900 to-black',
    borderColor: 'border-sky-400/80',
    textColor: 'text-sky-300',
    accentColor: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.65)',
    glowColorSoft: 'rgba(56, 189, 248, 0.25)',
    hpPoints: 4,
  },
  {
    level: 3,
    name: 'Volante',
    shortName: 'Volante',
    era: 'Dirección & Guiado',
    yearRange: 'Fase III',
    description: 'Aro de control direccional y brazos de mando para maniobrar con máxima precisión.',
    image: '3.png',
    bgGradient: 'from-amber-950 via-stone-900 to-black',
    borderColor: 'border-amber-400/80',
    textColor: 'text-amber-300',
    accentColor: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.65)',
    glowColorSoft: 'rgba(245, 158, 11, 0.25)',
    hpPoints: 8,
  },
  {
    level: 4,
    name: 'Chasis',
    shortName: 'Chasis',
    era: 'Bastidor & Plataforma',
    yearRange: 'Fase IV',
    description: 'Estructura rígida de largueros y travesaños reforzados que soporta la masa del vehículo.',
    image: '4.png',
    bgGradient: 'from-emerald-950 via-zinc-900 to-black',
    borderColor: 'border-emerald-400/80',
    textColor: 'text-emerald-300',
    accentColor: '#10b981',
    glowColor: 'rgba(16, 185, 129, 0.65)',
    glowColorSoft: 'rgba(16, 185, 129, 0.25)',
    hpPoints: 16,
  },
  {
    level: 5,
    name: 'Auto Clásico 20s',
    shortName: 'Auto Clásico 20s',
    era: 'Años 20: Producción en Serie',
    yearRange: '1920 - 1935',
    description: '¡El primer automóvil completo! Chasis alto, faros redondos y carrocería vintage clásica.',
    image: '5.png',
    bgGradient: 'from-amber-950 via-yellow-950 to-zinc-950',
    borderColor: 'border-amber-400',
    textColor: 'text-amber-300',
    accentColor: '#fbbf24',
    glowColor: 'rgba(251, 191, 36, 0.75)',
    glowColorSoft: 'rgba(251, 191, 36, 0.35)',
    hpPoints: 32,
  },
  {
    level: 6,
    name: 'Taller',
    shortName: 'Taller',
    era: 'Ingeniería & Modificación',
    yearRange: 'Fase V',
    description: 'Instalación de ensamblaje artesanal, herramental de precisión y optimización de rendimiento.',
    image: '6.png',
    bgGradient: 'from-orange-950 via-zinc-900 to-black',
    borderColor: 'border-orange-400/80',
    textColor: 'text-orange-300',
    accentColor: '#f97316',
    glowColor: 'rgba(249, 115, 22, 0.65)',
    glowColorSoft: 'rgba(249, 115, 22, 0.25)',
    hpPoints: 64,
  },
  {
    level: 7,
    name: 'Sedán 50s',
    shortName: 'Sedán 50s',
    era: 'Años 50: Edad Dorada Neón',
    yearRange: '1950 - 1960',
    description: 'Silueta aerodinámica reluciente con contornos de neón cian brillante sobre carrocería oscura.',
    image: '7.png',
    bgGradient: 'from-cyan-950 via-sky-950 to-zinc-950',
    borderColor: 'border-cyan-400',
    textColor: 'text-cyan-200',
    accentColor: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.85)',
    glowColorSoft: 'rgba(56, 189, 248, 0.4)',
    hpPoints: 128,
  },
  {
    level: 8,
    name: 'Motor V8',
    shortName: 'Motor V8',
    era: 'Potencia & Combustión V8',
    yearRange: 'Fase VI',
    description: 'Bloque de ocho cilindros en V con carburador de alto flujo y compresión extrema.',
    image: '8.png',
    bgGradient: 'from-red-950 via-zinc-900 to-black',
    borderColor: 'border-red-500/85',
    textColor: 'text-red-300',
    accentColor: '#ef4444',
    glowColor: 'rgba(239, 68, 68, 0.75)',
    glowColorSoft: 'rgba(239, 68, 68, 0.35)',
    hpPoints: 256,
  },
  {
    level: 9,
    name: 'Muscle Car 70s',
    shortName: 'Muscle Car 70s',
    era: 'Años 70: Furia de Caballos de Fuerza',
    yearRange: '1968 - 1978',
    description: 'Potente Dodge Challenger con toma de aire elevada, alerón y contornos neón naranja vibrante.',
    image: '9.png',
    bgGradient: 'from-orange-950 via-amber-950 to-zinc-950',
    borderColor: 'border-orange-500',
    textColor: 'text-orange-200',
    accentColor: '#f97316',
    glowColor: 'rgba(249, 115, 22, 0.85)',
    glowColorSoft: 'rgba(249, 115, 22, 0.45)',
    hpPoints: 512,
  },
  {
    level: 10,
    name: 'Alerón',
    shortName: 'Alerón',
    era: 'Carga Aerodinámica & Downforce',
    yearRange: 'Fase VII',
    description: 'Ala de fibra de carbono para generar adherencia y estabilidad extrema a altas velocidades.',
    image: '10.png',
    bgGradient: 'from-purple-950 via-zinc-900 to-black',
    borderColor: 'border-purple-400/85',
    textColor: 'text-purple-300',
    accentColor: '#c084fc',
    glowColor: 'rgba(192, 132, 252, 0.75)',
    glowColorSoft: 'rgba(192, 132, 252, 0.35)',
    hpPoints: 1024,
  },
  {
    level: 11,
    name: 'Superdeportivo Moderno',
    shortName: 'Superdeportivo (2048)',
    era: 'Fibra de Carbono & Neón SVJ',
    yearRange: '2015 - 2025',
    description: '¡Hito 2048! Lamborghini SVJ con enorme alerón aerodinámico y contornos neón magenta.',
    image: '11.png',
    bgGradient: 'from-rose-950 via-pink-950 to-zinc-950',
    borderColor: 'border-rose-400',
    textColor: 'text-rose-100',
    accentColor: '#f43f5e',
    glowColor: 'rgba(244, 63, 94, 0.95)',
    glowColorSoft: 'rgba(244, 63, 94, 0.5)',
    hpPoints: 2048,
    milestone: 2048,
  },
  {
    level: 12,
    name: 'Neumático',
    shortName: 'Neumático',
    era: 'Competición & Máxima Tracción',
    yearRange: 'Fase VIII',
    description: 'Compuesto blando de alta temperatura con surcos radiales para adherencia total en pista.',
    image: '12.png',
    bgGradient: 'from-indigo-950 via-zinc-900 to-black',
    borderColor: 'border-indigo-400/85',
    textColor: 'text-indigo-300',
    accentColor: '#818cf8',
    glowColor: 'rgba(129, 140, 248, 0.8)',
    glowColorSoft: 'rgba(129, 140, 248, 0.4)',
    hpPoints: 4096,
  },
  {
    level: 13,
    name: 'Hipercoche Conceptual',
    shortName: 'Hipercoche (4096)',
    era: 'Propulsión Cuántica & Híbrida',
    yearRange: '2030 - 2050',
    description: '¡Hito 4096! Diseño alienígena aerotáctil, inteligencia artificial neuronal y aceleración sin fricción.',
    image: '13.png',
    bgGradient: 'from-fuchsia-950 via-purple-950 to-zinc-950',
    borderColor: 'border-fuchsia-400',
    textColor: 'text-fuchsia-200',
    accentColor: '#e879f9',
    glowColor: 'rgba(232, 121, 249, 0.9)',
    glowColorSoft: 'rgba(232, 121, 249, 0.5)',
    hpPoints: 8192,
    milestone: 4096,
  },
  {
    level: 14,
    name: 'Nave Espacial / Primer Vehículo Volador',
    shortName: 'Nave Espacial (16,384)',
    era: 'Primer Vehículo Volador',
    yearRange: 'Año 3000+',
    description: '¡Hito 16,384! Nave orbital aerodinámica impulsada por propulsión estelar. El primer paso fuera de la atmósfera terrestre.',
    image: '14.png',
    bgGradient: 'from-amber-950 via-rose-950 to-purple-950',
    borderColor: 'border-yellow-300',
    textColor: 'text-yellow-200',
    accentColor: '#fde047',
    glowColor: 'rgba(253, 224, 71, 1.0)',
    glowColorSoft: 'rgba(253, 224, 71, 0.7)',
    hpPoints: 16384,
    milestone: 16384,
  },
  {
    level: 15,
    name: 'Hipercoche Conceptual Render 3D',
    shortName: 'Hipercoche 3D (32,768)',
    era: 'Render 3D • Neón Cyan & Magenta',
    yearRange: 'Año 2060',
    description: '¡Hito 32,768! Superdeportivo exótico esculpido con contornos luminosos cian y magenta, aerodinámica activa y cabina de policarbonato traslúcido.',
    image: '15.png',
    bgGradient: 'from-cyan-950 via-fuchsia-950 to-zinc-950',
    borderColor: 'border-cyan-400',
    textColor: 'text-cyan-200',
    accentColor: '#06b6d4',
    glowColor: 'rgba(6, 182, 212, 0.95)',
    glowColorSoft: 'rgba(232, 121, 249, 0.5)',
    hpPoints: 32768,
    milestone: 32768,
  },
  {
    level: 16,
    name: 'Súper Auto Legendario Estilo Batimóvil Cyberpunk',
    shortName: 'Batimóvil Cyberpunk (65,536)',
    era: 'Blindaje Stealth & Turbina Violeta',
    yearRange: 'Año 2085',
    description: '¡Hito 65,536! Carrocería blindada de fibra de carbono angular, alerones dobles y turbina de reacción trasera con estela de plasma violeta.',
    image: '16.png',
    bgGradient: 'from-zinc-950 via-purple-950 to-black',
    borderColor: 'border-purple-400',
    textColor: 'text-purple-200',
    accentColor: '#a855f7',
    glowColor: 'rgba(168, 85, 247, 0.95)',
    glowColorSoft: 'rgba(168, 85, 247, 0.5)',
    hpPoints: 65536,
    milestone: 65536,
  },
  {
    level: 17,
    name: 'Auto Volador con Propulsores de Neón',
    shortName: 'Auto Volador Neón (131,072)',
    era: 'Propulsión Antigravedad de Neón',
    yearRange: 'Año 2120',
    description: '¡Hito 131,072! Chasis súper aerodinámico sustentado por 4 propulsores de neón cian en anillo y estelas de vórtice de flujo cuántico.',
    image: '17.png',
    bgGradient: 'from-cyan-950 via-sky-950 to-zinc-950',
    borderColor: 'border-sky-400',
    textColor: 'text-sky-200',
    accentColor: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 1.0)',
    glowColorSoft: 'rgba(6, 182, 212, 0.6)',
    hpPoints: 131072,
    milestone: 131072,
  },
  {
    level: 18,
    name: 'Portal de Hiperviaje Automotriz de la Cochera',
    shortName: 'Portal Infinito (262,144+)',
    era: 'Modo Infinito • Dios de la Cochera',
    yearRange: 'Singularidad Automotriz Eterna',
    description: '¡Hito Supremo 262,144! Stargate automotriz definitivo en la cochera espacial, con anillos de hiperviaje cuántico y aceleración dimensional infinita.',
    image: '18.png',
    bgGradient: 'from-amber-950 via-purple-950 to-cyan-950',
    borderColor: 'border-yellow-300',
    textColor: 'text-yellow-200',
    accentColor: '#fde047',
    glowColor: 'rgba(253, 224, 71, 1.0)',
    glowColorSoft: 'rgba(245, 158, 11, 0.8)',
    hpPoints: 262144,
    milestone: 262144,
  },
];

export function getEvolutionByLevel(level: number): EvolutionLevel {
  const found = EVOLUTION_LEVELS.find((e) => e.level === level);
  if (found) return found;

  // Modo Infinito: Procedural beyond Level 18
  const baseHp = Math.pow(2, level);
  return {
    level,
    name: `Súper Auto Hiperdimensional Mk-${level}`,
    shortName: `Súper Auto Mk-${level}`,
    era: 'Modo Infinito • Trascendencia Eterna',
    yearRange: `Año ${2120 + (level - 18) * 100}`,
    description: 'Evolución automotriz suprema en estilo render 3D impulsada por energía taquiónica de la cochera infinita.',
    image: '18.png',
    bgGradient: 'from-amber-950 via-purple-950 to-black',
    borderColor: 'border-yellow-300',
    textColor: 'text-yellow-100',
    accentColor: '#fbbf24',
    glowColor: 'rgba(251, 191, 36, 1.0)',
    glowColorSoft: 'rgba(251, 191, 36, 0.8)',
    hpPoints: baseHp,
  };
}
